name: ramada-app
services:
  app:
    image: golang:1.23.3
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    command: go run cmd/main.go
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: ramada_db
    image: mysql:8.0.40
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysqlData:/var/lib/mysql

volumes:
  mysqlData: {}
